stages:
  - Build
  - "Set Final GitHub Status"
  

variables:
  GITHUB_ORG: "tsubashi"
  GITHUB_REPO_NAME: "github-webhook-test"
  

"Set Pending Status (GitHub)":
  stage: Build
  image: curlimages/curl:7.70.0
  script:
    - curl -X POST -H "Content-Type:application/json" -H "Authorization:token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_ORG/$GITHUB_REPO_NAME/statuses/$CI_COMMIT_SHA" --data "{\"state\":\"pending\", \"target_url\":\"$CI_JOB_URL\", \"description\":\"Running Commit\", \"context\":\"AquaGit\"}"


build:
  stage: Build
  image: alpine
  script:
    - echo "Build & Test Here!"
    - sleep 10

"Success":
  stage: "Set Final GitHub Status"
  image: curlimages/curl:7.70.0
  script:
    - curl -X POST -H "Content-Type:application/json" -H "Authorization:token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_ORG/$GITHUB_REPO_NAME/statuses/$CI_COMMIT_SHA" --data "{\"state\":\"success\", \"target_url\":\"$CI_JOB_URL\", \"description\":\"All Green\", \"context\":\"AquaGit\"}"
  when: on_success

"Failure":
  stage: "Set Final GitHub Status"
  image: curlimages/curl:7.70.0
  script:
    - curl -X POST -H "Content-Type:application/json" -H "Authorization:token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_ORG/$GITHUB_REPO_NAME/statuses/$CI_COMMIT_SHA" --data "{\"state\":\"failure\", \"target_url\":\"$CI_JOB_URL\", \"description\":\"Job failed\", \"context\":\"AquaGit\"}"
  when: on_failure

