stages:
  - mirror
  - build

variables:
  GITHUB_REPO_URL: "git@github.com:tsubashi/github-webhook-test.git"
  GITLAB_REPO_URL: "git@git.aquaveo.com:cscott/github-webhook-test.git"

mirror:
  stage: mirror
  image: centos:7
  script:
    # Set up SSH
    - yum -y install openssh-clients git
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${MIRROR_KEY}")   
    - mkdir -p ~/.ssh
    - echo "$SSH_HOSTKEYS" > ~/.ssh/known_hosts

    # Mirror the Repo
    - if [ -e github ]; then rm -rf github; fi
    - echo "Mirroring from ${GITHUB_REPO_URL}"
    - git clone --bare ${GITHUB_REPO_URL} github
    - cd github
    - git push --mirror ${GITLAB_REPO_URL}
    - cd ..
    - rm -rf github
  only: 
    - triggers

build:
  stage: build
  script:
    - echo "Build & Test Here!"
    - echo "WOOOO!"
    - curl -X POST -H "Content-Type: application/json" -H "Authorization: token acd9e49cd2b49ca5cc8222785ce51a84791dd4b5" https://github.com/repos/tsubashi/github-webhook-test/statuses/${CI_COMMIT_SHA} --data '{"state": "success", "target_url": "${CI_JOB_URL}", "description": "The build succeeded!", "context": "continuous-integration/gitlab-ci"}'
  except: 
    - trigger
