stages:
  - mirror
  - build

variables:
  - GITHUB_REPO_URL = "https://github.com/tsubashi/github-webook-test.git"

mirror:
  stage: mirror
  script:
    - echo "Mirroring from ${GITHUB_REPO_URL}"
  only: triggers

build:
  stage: build
  script:
    - echo "Build & Test Here!"
  except: triggers
